name: create pr

on: [ create ]

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set branch name
          #   run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
          #   run: echo "BRANCH=${GITHUB_HEAD_REF##/}}"
          run: echo ${GITHUB_REF_NAME}
        - name: create pr
          run: |
            gh pr create -B main -H ${GITHUB_REF_NAME} --title "Documentation to merge" --body 'Created by GitHub action' 
            gh pr merge --admin --merge --delete-branch ${GITHUB_REF_NAME}
          env:
            GH_TOKEN: ${{ github.token }}


